### ISSUE TITLE
Bug: Bot tries to handle the question instead of the response

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/gptSurveySummarizer#27]
When testing the command /Gptsurvey view, in a long question (length of 89 characters), the bot threw an error:

![image](https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/4c064805-e0a8-497d-9b77-8d635bf364ef)

Marton checked the error and informed:

It says that the response it is trying to handle is too long. The code has to be adjusted so it can handle strings longer than 100 characters.
But I see it is trying to handle the question instead of the response

```
│   Invalid string length                                                                                                                                     │
│                                                                                                                                                             │
│   Expected: expected.length <= 100                                                                                                                          │
│                                                                                                                                                             │
│   Received:                                                                                                                                                 │
│   | 'respondButton-1- Do you agree with the approach presented in the blogpost? (1 is least agreement, 5 is most)' 
```

 It seems to be a bug in the code that makes the application to parse the inputs of the users incorrectly

**Comment by es92** [comment]
Fixed now on main
