### ISSUE TITLE
Bug: Bot is not categorizing responses (April 25th)

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/gptSurveySummarizer#28]
We started the survey yesterday April 24th, some users replied today April 25th, however the bot is not categorizing the replies.

<img width="673" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/7bf5a520-f041-4c4b-8632-6600fd42ec07">

**Comment by es92** [comment]
It seems this was a combination of two bugs:

1) Sometimes the OpenAI API, even though requested to return JSON, may not be returning valid JSON
2) If the summarizer has an error, it stops the loop of re-computing summaries

I have both of these fixed in a PR that will merge shortly
