### ISSUE TITLE
Enable timestamps on logging

### ISSUE THREAD

**Issue by Smorci** [MinaFoundation/gptSurveySummarizer#29]
For testing it is really useful to have timestamps in the logs, so we can map error messages to action on the discord channel.

**Comment by berkingurcan** [comment]
Solved in https://github.com/MinaFoundation/gptSurveySummarizer/pull/56

**Comment by CristinaEche** [comment]
Duplicated and unable to add it to the PR 56

**Comment by CristinaEche** [comment]
Duplicated and unable to add it to the PR 56
