### ISSUE TITLE
May 2nd: issues with the creation of a multi-response question

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/gptSurveySummarizer#39]
Hi!
Not sure if it is because we already have a list of questions, on the survey channel:

<img width="1093" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/b91967ea-ce42-4b37-b272-aad79ccfa875">

But today, when i try to use the **_/gptsurvey create-multi-response_**  to create a new survey is not letting me use it, it is showing me the simple response option:

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/93b1eadc-b112-473b-9152-cab366113b0a

**Comment by es92** [comment]
I think this is intended behavior -- if you create the survey, you should be able to see when responding that multiple responses can be provided.

We could structure it differently to make it more clear too

**Comment by CristinaEche** [comment]
Tested, working correctly, thanks!

**Comment by CristinaEche** [comment]
Tested, working correctly, thanks!
