### ISSUE TITLE
Add LOGLEVEL with Timestamps to logs

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#48]
As @johnmarcou requested, it is good practice to add log level for logs with timestamps. Can be used: https://www.npmjs.com/package/loglevel

**Comment by berkingurcan** [comment]
Solved: https://github.com/MinaFoundation/gptSurveySummarizer/pull/56
But need to check how to configure in ENV, because I set the log level in here:

https://github.com/MinaFoundation/gptSurveySummarizer/pull/56/commits/89d4b76b7f4c291bf306e2c840a176c1feffd5fb#diff-4c57e1eda9c7d9cb0e46d669ec83dfb50a214e0263ddef7b2245d5a5bc4d57d9

Where should I get the LOG LEVEL value? @johnmarcou

**Comment by berkingurcan** [comment]
<img width="674" alt="Screenshot 2024-06-10 at 15 25 02" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/70534820/83585ae6-8c56-42d3-a54c-bcc15e2d2c54">

**Comment by johnmarcou** [comment]
> Solved: #56 But need to check how to configure in ENV, because I set the log level in here:
> 
> [89d4b76#diff-4c57e1eda9c7d9cb0e46d669ec83dfb50a214e0263ddef7b2245d5a5bc4d57d9](https://github.com/MinaFoundation/gptSurveySummarizer/commit/89d4b76b7f4c291bf306e2c840a176c1feffd5fb#diff-4c57e1eda9c7d9cb0e46d669ec83dfb50a214e0263ddef7b2245d5a5bc4d57d9)
> 
> Where should I get the LOG LEVEL value? @johnmarcou

@berkingurcan Usually it's nice to have an environment variable to set the logging level, such as `GPT_SURVEY_SUMMARIZER_LOG_LEVEL`, or may be just `GSS_LOG_LEVEL`.
