### ISSUE TITLE
UX Proposal: Forum Channel for Surveys

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#49]
Hello, 
We have new Survey UX Proposal with @CristinaEche:

When survey creator create a Survey from another channel, Surveys will be automatically displayed on Forum Channels as Threads with better UI. For example:
<img width="879" alt="Screenshot 2024-05-29 at 15 37 37" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/70534820/cdfed854-e4e1-4f10-bb4a-262daa2b30cd">
<img width="586" alt="Screenshot 2024-05-29 at 15 39 43" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/70534820/b03efe4c-df6e-46b8-9919-00a7e24b58c7">

It is basically implemented on this branch: https://github.com/berkingurcan/gptSurveySummarizer/tree/thread-post

**User flow is like this:**
- Survey creator creates survey on another text channel(it does not matter which one)
- When the survey, created bot automatically posts the survey as a thread to forum channel with Survey Title, Survey Description and Respond Button.
- People will see the Survey Thread
- They will respond

**Comment by CristinaEche** [comment]
When using multi response creation modal: we need to match only 45 char. for each question.

**Comment by berkingurcan** [comment]
> When using multi response creation modal: we need to match only 45 char. for each question.

It is in #45 

For now, I can't see better solution.

**Comment by es92** [comment]
This makes a lot of sense! Approved by me!

**Comment by berkingurcan** [comment]
https://github.com/MinaFoundation/gptSurveySummarizer/pull/56
