### ISSUE TITLE
View Summaries: Add command for displaying the summarised results in threads

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/gptSurveySummarizer#51]
@berkingurcan 

**- New command:** Add an option to display summarized responses without the raw data, so we can share the latest summary with the community.

**- Handle anonymity:** We also need the bot to avoid displaying discord handles in the summary for example: 

> 🇦 General Approval [2 responses]
> Expressions of strong agreement and anticipation for the governance experiment.
> 
> Responses in the subtopic of General Approval indicate strong support for the proposals aimed at democratic governance for Mina. Respondents like _Roy Nakakawa and Naamah8064_ express strong agreement, highlighting the proposals' significance while acknowledging their ambition as positive. However, _Naamah8064_ raises a concern regarding the language barrier, suggesting the addition of multilingual representatives and translations of key documents to ensure inclusivity.

**Comment by CristinaEche** [comment]
Also adding a high level summary for executive directors and stakeholders , to have a quick read

**Comment by CristinaEche** [comment]
@berkingurcan we need to make sure this summaries are posted in threads and updated automatically each time the autopost release a new summary result. LMK when we are starting this in order to have a flow well defined. tks!

**Comment by berkingurcan** [comment]
Need to be tested. https://github.com/berkingurcan/gptSurveySummarizer/tree/view-summaries
If ok I will PR 🍡

**Comment by CristinaEche** [comment]
New command: Add an option to display summarized responses without the raw data, so we can share the latest summary with the community.
 Handle anonymity: We also need the bot to avoid displaying discord handles in the summary.
 Adding a high level summary for executive directors and stakeholders , to have a quick read.

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/b325c60e-e16e-40bf-b059-aa88886ecd47
