### ISSUE TITLE
feature command delete surveys

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#52]
Implement a new commands for deleting surveys.

**Comment by CristinaEche** [comment]
Tested the feature with positive results.  adding 2 evidences.

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/f72fc810-df67-4c02-91d4-b80a0687e920

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/405d7f64-311e-4925-8965-0fc73ac2b868

**Comment by berkingurcan** [comment]
It is in this branch:
https://github.com/berkingurcan/gptSurveySummarizer/tree/add-command-delete-surveys
