### ISSUE TITLE
feature command edit/update surveys and their components

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#53]
Is there a difference between editing and updating? @es92 @CristinaEche 
If there is, can you give an example?

**Comment by CristinaEche** [comment]
Hello @berkingurcan, it is the same, the idea is to be able to retrieve the modal of a published survey and edit or update any information previously created.

**Comment by berkingurcan** [comment]
Okay!

**Comment by CristinaEche** [comment]
We are testing 5 scenarios:

1- editing questions and descriptions without responses - single and multi response testing- OK
2- editing questions and descriptions with responses single and multi - with responses- OK
3- Multiresponse: delete questions - if only one questions it turns into single question modal- OK
4- Multiresponse : add questions - not able to do it so far- TBC

CC: @es92

**Comment by CristinaEche** [comment]
Evidence:

Multiresponse: delete questions - if only one questions it turns into single question modal

<img width="1186" alt="Screenshot 2024-06-04 at 14 26 22" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/18c0f2a7-e874-4b87-bf7d-dda50f6881fe">

Multiresponse changing description from 123 to 456

<img width="1186" alt="Screenshot 2024-06-04 at 14 19 06" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/6f9f4834-147a-4783-8925-31fc981fd3b0">

<img width="1186" alt="Screenshot 2024-06-04 at 14 18 29" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/ebe2391e-d8c9-4a94-b594-96578354f0d7">

<img width="1186" alt="Screenshot 2024-06-04 at 14 17 15" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/674bd982-39f9-4388-bb02-af3433fc5e62">



Videos of single response testing


https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/9b6b8f55-dcf7-40e9-84ca-126e4efa744f


https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/6a89d783-e179-4aa9-906e-fff1a9be3dbc

**Comment by berkingurcan** [comment]
TODO!: I have an error while adding more questions to initial question number while editing:
```
Unhandled exception: ValidationError > s.string
  Expected a string primitive

  Received:
  | undefined

    at _StringValidator.handle (/Users/berkingurcan/Documents/gptSurveySummarizer/node_modules/@sapphire/shapeshift/src/validators/StringValidator.ts:23:73)
    at _StringValidator.parse (/Users/berkingurcan/Documents/gptSurveySummarizer/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
    at TextInputBuilder.setValue (/Users/berkingurcan/Documents/gptSurveySummarizer/node_modules/@discordjs/builders/src/components/textInput/TextInput.ts:117:36)
    at <anonymous> (/Users/berkingurcan/Documents/gptSurveySummarizer/src/commands/handleRespondButton.ts:68:12)
    at Array.map (<anonymous>)
    at handleRespondButton (/Users/berkingurcan/Documents/gptSurveySummarizer/src/commands/handleRespondButton.ts:62:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.<anonymous> (/Users/berkingurcan/Documents/gptSurveySummarizer/src/bot.ts:110:9)
```

**Comment by CristinaEche** [comment]
Multiresponse editing and question deletion tested one more time, here the evidences:

<img width="496" alt="Screenshot 2024-06-05 at 14 36 03" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/68cccb53-ed40-4134-84fd-472996b1d386">


https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/c8f85c87-e731-49c7-842f-2a0cfb2ff8a3



https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/4d869fae-eb5d-4efa-b188-1c0100a233cc

**Comment by berkingurcan** [comment]
> TODO!: I have an error while adding more questions to initial question number while editing:
> 
> ```
> Unhandled exception: ValidationError > s.string
>   Expected a string primitive
> 
>   Received:
>   | undefined
> 
>     at _StringValidator.handle (/Users/berkingurcan/Documents/gptSurveySummarizer/node_modules/@sapphire/shapeshift/src/validators/StringValidator.ts:23:73)
>     at _StringValidator.parse (/Users/berkingurcan/Documents/gptSurveySummarizer/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
>     at TextInputBuilder.setValue (/Users/berkingurcan/Documents/gptSurveySummarizer/node_modules/@discordjs/builders/src/components/textInput/TextInput.ts:117:36)
>     at <anonymous> (/Users/berkingurcan/Documents/gptSurveySummarizer/src/commands/handleRespondButton.ts:68:12)
>     at Array.map (<anonymous>)
>     at handleRespondButton (/Users/berkingurcan/Documents/gptSurveySummarizer/src/commands/handleRespondButton.ts:62:8)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Client.<anonymous> (/Users/berkingurcan/Documents/gptSurveySummarizer/src/bot.ts:110:9)
> ```

Solved.

**Comment by CristinaEche** [comment]
FYI:  detected that we cannot use "-" in a survey title
