### ISSUE TITLE
Implement Active/Passive and Timeframe Features for Surveys

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#54]
**Description:**
Add functionality to mark surveys as active or passive and to set timeframes for survey availability. This enhancement will allow moderators to manage the availability of surveys and automate their activation and deactivation based on specified timeframes.

**Requirements:**
**1. Active/Passive Status for Surveys**
- [x] Add a new field status to the survey model to store the active/passive state. Bool.
- [x] Implement commands for moderators to change the status of surveys.
- [x] Implement both restriction to respond and while responding for only active surveys should be visible to users for responses to: 
```ts 
else if (interaction.isAutocomplete()) {
      const surveys = await redisClient.sMembers("surveys");
      const focusedValue = interaction.options.getFocused();
      const filtered = surveys.filter((choice) =>
        choice.startsWith(focusedValue),
      );
      const start = Math.max(filtered.length - 25, 0);
      const limitedChoices = filtered.slice(start);

      await interaction.respond(
        limitedChoices.map((choice) => ({ name: choice, value: choice })),
      );
    }
```

**2. Timeframe Feature**
- [x] Provide an ui in create and edit commands for moderators to set the timeframe for surveys.
- [x] Add new fields endTime to the survey model to store the timeframe during which the survey is active.
- [x] Implement checks to automatically activate and deactivate surveys based on the current date and time relative to  endTime.

**Comment by CristinaEche** [comment]
@berkingurcan  LMK when we can finish this testing, since in Friday we set some times for surveys , they should be deactivated by today.

**Comment by CristinaEche** [comment]
Today we have tested:

- Set expire date
- Change expire date
- Extend expire date
- Deactivate - activate an active survey
- Activate -  an inactive survey - deactivate again 

Evidence:

- Set expire date: (example is settled with wrong date= Inf)

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/fb269d8e-0b43-41e9-ba90-7207aaae5fd0

- Change expire date: (changes Inf to a real date)

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/827d5d70-1d1b-45ca-a680-badb4b663729

- Extend expire date (video with reduced quality)

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/b104fba5-f3db-4a2b-946d-1f4dabef6e5b

NOTE: we can post the same survey in different channels and if we deactivate the survey it will be deactivated in all channels.

- Deactivate - activate an active survey

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/9897b3d4-7080-42cf-8c81-8fe106daf3d7

- Activate -  an inactive survey - deactivate again 

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/7f59fb4a-57c5-4a89-bea9-e23198810915



CC: @es92
