### ISSUE TITLE
Create Survey: Improve Thread Posting Features: edit , deactivate, activate and delete surveys 

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#61]
Currently, we have thread posting feature. When a survey created, it posts the survey to forum channel. 

**UI Improvements:**

- [x] Develop good looking interface, perhaps embeds for posted.

**UX Improvements:**

- [x] Make optional the posting survey to forum channel.
- [x] Develop case and related improvements when the survey is **edited**: _Title, Description, Expire Time_.
- [x] Develop case and related improvements when the survey is **deleted**.
- [x] Develop case and related improvements when the survey is **deactivated** and **reactivated**.
- [x] Develop Auto posting feature compatible with thread posting: **Solved, in thread need to use start auto posting command**: https://github.com/berkingurcan/gptSurveySummarizer/tree/view-summaries

**Comment by berkingurcan** [comment]
@CristinaEche You can propose user flow for UX Improvements above.

**Comment by CristinaEche** [comment]
@berkingurcan https://github.com/MinaFoundation/gptSurveySummarizer/issues/62 this is ofr the bug detected yesterday when editing a posted survey

**Comment by CristinaEche** [comment]
@berkingurcan This issue is also related to threads posting: https://github.com/MinaFoundation/gptSurveySummarizer/issues/51

**Comment by berkingurcan** [comment]
Added embed for goog looking :)

<img width="559" alt="Screenshot 2024-06-13 at 15 58 51" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/70534820/e9443059-48e5-4b28-bb4e-0725c04d99ab">

**Comment by berkingurcan** [comment]
Solved: #65

**Comment by berkingurcan** [comment]
https://github.com/MinaFoundation/gptSurveySummarizer/issues/51 Need to make sure this summaries are posted in threads and updated automatically each time the autopost release a new summary result.

**Comment by CristinaEche** [comment]
Make optional the posting survey to forum channel.

<img width="639" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/be012c23-d975-4fb0-85fe-4a5e7037430d">

**Comment by CristinaEche** [comment]
Develop good looking interface, perhaps embeds for posted.

<img width="1374" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/3cf987a3-f361-45a5-8b93-307323204df7">

**Comment by CristinaEche** [comment]
Develop case and related improvements when the survey is deactivated and reactivated.


https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/8f3edfb5-166b-4545-a621-a9b96c5197a2

**Comment by CristinaEche** [comment]
Develop Auto posting feature compatible with thread posting: Solved, in thread need to use start auto posting command

3.47pm requested autoposting:

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/1d6a8ce2-153f-462f-a715-8a17aa1e48ec

4.34pm. replaced previous posts :
<img width="1022" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/47d8ce19-8cf6-494a-85b5-a1ccedb715ac">

**Comment by CristinaEche** [comment]
Develop case and related improvements when the survey is deleted.

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/4c66c6a5-29df-4119-9f21-6c91777bfb37

**Comment by CristinaEche** [comment]
Develop case and related improvements when the survey is edited: Title, Description, Expire Time.

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/68440f73-a7e6-4732-ab45-fe361ee47529
