### ISSUE TITLE
BUG: Edit Survey title and interaction failed after edition.

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/gptSurveySummarizer#62]
Once a Survey is posted in the forum channel, if we edit the the survey title , this title is not being updated and the actual survey gets error message when is responded:

Example: changed Survey title to number 5 - It's original name was number 4 

<img width="517" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/bff5e6a4-8b80-45ee-9526-6eea00a12a47">

<img width="1120" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/29ac9392-7cd1-4122-ad8a-c4cfefaf5740">

In the posted survey :  number 4 , you do not see the title changes, and if you try to respond it , the interaction fails

<img width="1120" alt="image" src="https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/55ac357f-6c83-4387-883b-e980378e81da">

**Comment by CristinaEche** [comment]
Posted _By @berkingurcan:

**Fix Bugs:**

- [ ] Edited, deleted, deactivated survey interaction bugs.

**Comment by berkingurcan** [comment]
Solved: #65

**Comment by CristinaEche** [comment]
Edit survey title and check response interaction after editing:

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/389f9a05-bfa0-44ac-b739-7932b27b5752

**Comment by CristinaEche** [comment]
deleted & deactivated survey interaction bugs solved.

Delete:
https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/260fb0bc-6559-4715-bf4a-855a24db2d56

Deactivate:

https://github.com/MinaFoundation/gptSurveySummarizer/assets/166489186/19cd1b8d-ebb5-449e-814a-7289e37d1583



also solved in Issue: https://github.com/MinaFoundation/gptSurveySummarizer/issues/61
