### ISSUE TITLE
UX Improvement: user should not be able to view or respond to a survey that does not exist.

### ISSUE THREAD

**Issue by es92** [MinaFoundation/gptSurveySummarizer#7]
See TODOs [here](https://github.com/es92/gptSurveySummarizer/blob/96ec740433b73348d77d4e41b79a74ee1f10a05b/bot.js#L41) and [here](https://github.com/es92/gptSurveySummarizer/blob/96ec740433b73348d77d4e41b79a74ee1f10a05b/bot.js#L52).

**Comment by berkingurcan** [comment]
It is solved in: https://github.com/MinaFoundation/gptSurveySummarizer/issues/54 and https://github.com/MinaFoundation/gptSurveySummarizer/issues/52
