### ISSUE TITLE
Move the codebase to typescript and add types

### ISSUE THREAD

**Issue by es92** [MinaFoundation/gptSurveySummarizer#8]

**Comment by berkingurcan** [comment]
I can also do that, is it okay? @es92 @remigiusz-antczak

**Comment by es92** [comment]
Yep would be great!

**Comment by berkingurcan** [comment]
Solved for bot.js and its handlers by https://github.com/MinaFoundation/gptSurveySummarizer/pull/44
Added temporary types.
I have not changed to Typescript in summarizer. I will change it while doing the work about summarizer.
